name: DVWA

on: 
  workflow_dispatch:

jobs:
  
  DVWA:
    name: DVWA
    runs-on: ubuntu-latest
    env: 
      IMAGE_REPO_NAME: "dvwapub"
      IMAGE_TAG: "std039"
      REPOSITORY_URI: "public.ecr.aws/f9n2h3p5/dvwapub"
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}}          

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Logging into AWS ECR
      run: |
        aws ecr-public get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI} 

    - name: Building image
      run: |
        docker build "${IMAGE_REPO_NAME}:${IMAGE_TAG}-${env.BUILD_NUMBER}" 

    - name: Pushing to ECR
      run: |
        docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG}-${env.BUILD_NUMBER} ${REPOSITORY_URI}:$IMAGE_TAG-${env.BUILD_NUMBER]
        docker push ${REPOSITORY_URI}:${IMAGE_TAG}-${env.BUILD_NUMBER}