name: DVWA

on: 
  workflow_dispatch:

jobs:
  
  DVWA:
    name: DVWA
    runs-on: ubuntu-latest
    env: 
      IMAGE_REPO_NAME: "dvwa"
      IMAGE_TAG: "app"
      REPOSITORY_URI: "984954827291.dkr.ecr.us-east-1.amazonaws.com/dvwa"
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Logging into AWS ECR
      run: |
        aws ecr-public get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}

    - name: Building image
      run: |
        docker build . -t "${IMAGE_REPO_NAME}:${IMAGE_TAG}-$GITHUB_RUN_NUMBER"
        docker build . -t ${IMAGE_REPO_NAME}:latest
    
    - name: Pushing to ECR
      run: |
        docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG}-$GITHUB_RUN_NUMBER ${REPOSITORY_URI}:$IMAGE_TAG-$GITHUB_RUN_NUMBER
        docker push ${REPOSITORY_URI}:${IMAGE_TAG}-$GITHUB_RUN_NUMBER
        docker tag ${IMAGE_REPO_NAME}:latest ${REPOSITORY_URI}:latest
        docker push ${REPOSITORY_URI}:latest