name: Terraform apply

on: 
  workflow_dispatch:

jobs:
  
  Terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env: 
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

    - name: Terraform Init
      run: |
        cd terraform/
        terraform init -backend-config backend.tfvars

    - name: Terraform Plan
      run: |
        cd terraform/
        terraform plan -var-file terraform.tfvars -out terraform.tfplan

    - name: Terraform Apply
      run: |
        cd terraform/
        terraform apply terraform.tfplan